### ISSUE TITLE
Issue reading 1.15 region.

### ISSUE THREAD

**Issue by ZombieStriker** [GameModsBR/Region-Manipulator#4]
Hello,

I've been using this util in one of my plugins, and while updating my server to 1.15, I started receiving the following error: `

>[21:25:55] [Server thread/WARN]: java.io.EOFException
[21:25:55] [Server thread/WARN]: 	at java.base/java.io.RandomAccessFile.readFully(Unknown Source)
[21:25:55] [Server thread/WARN]: 	at java.base/java.io.RandomAccessFile.readFully(Unknown Source)
[21:25:55] [Server thread/WARN]: 	at br.com.gamemods.regionmanipulator.RegionIO.readRegion(RegionIO.kt:63)
[21:25:55] [Server thread/WARN]: 	at br.com.gamemods.regionmanipulator.RegionIO.readRegion(RegionIO.kt:26)
[21:25:55] [Server thread/WARN]: 	at me.zombie_striker.chunkculler.Main.cullForWorld(Main.java:666)
[21:25:55] [Server thread/WARN]: 	at me.zombie_striker.chunkculler.Main.cullForWorld(Main.java:599)
[21:25:55] [Server thread/WARN]: 	at me.zombie_striker.chunkculler.Main.onDisable(Main.java:329)
[21:25:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[21:25:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:377)
[21:25:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:438)
[21:25:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:430)
[21:25:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:396)
[21:25:55] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:698)
[21:25:55] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:683)
[21:25:55] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:863)
[21:25:55] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)

My plugin worked on 1.14, and now this error appears whenever my plugin tries to read any chunk from my 1.15 world.

**Comment by Polyana-Fontes** [comment]
Hi, I tried to reproduce with a new 1.15.1 world but it worked. I think you might have a corrupt chunk somewhere, can you attach a MCA file which causes this issue?

I'm going to catch that exception, corrupt chunks shouldn't interrupt the entire region, so you will have more details about then with Region.getCorruptChunks()
